namespace MusicService.Migrations
{
    using Models;
    using System.Data.Entity.Migrations;

    internal sealed class Configuration : DbMigrationsConfiguration<MusicService.Models.MusicServiceContext>
    {
        public Configuration()
        {
            AutomaticMigrationsEnabled = false;
        }

        protected override void Seed(MusicService.Models.MusicServiceContext context)
        {
            context.Labels.AddOrUpdate(new Label[] {
                new Label() { LabelId = 1, Name = "Universal Music Group", FoundationYear = 1934, FounderName = "Lucian Grainge" },
                new Label() { LabelId = 2, Name = "Sony Music Entertainment", FoundationYear = 1929, FounderName = "Doug Morris" },
                new Label() { LabelId = 3, Name = "Warner Music Group", FoundationYear = 1958, FounderName = "Stephen Copper" }
            });

            context.Bands.AddOrUpdate(new Band[] {
                new Band() { BandId = 1, Name = "Avenged Sevenfold", Genre = "Heavy Metal", Country = "United States", LabelRefId = 1 },
                new Band() { BandId = 2, Name = "A B I S M O", Genre = "Stoner Metal", Country = "Brazil", LabelRefId = 1 },
                new Band() { BandId = 3, Name = "Bullet for My Valentine", Genre = "Heavy Metal", Country = "United States", LabelRefId = 1 },
                new Band() { BandId = 4, Name = "Breaking Benjamin", Genre = "Metal", Country = "United States", LabelRefId = 1 },
                new Band() { BandId = 5, Name = "Cannibal Corpse", Genre = "Death Metal", Country = "United States", LabelRefId = 1 },
                new Band() { BandId = 6, Name = "Chevelle", Genre = "Hard Rock", Country = "United States", LabelRefId = 2 },
                new Band() { BandId = 7, Name = "Disturbed", Genre = "Heavy Metal", Country = "United States", LabelRefId = 2 },
                new Band() { BandId = 8, Name = "Dagor Dagorath", Genre = "Symphonic Black Metal", Country = "Israel", LabelRefId = 2 },
                new Band() { BandId = 9, Name = "Eagles of Death Metal", Genre = "Hard Rock", Country = "United States", LabelRefId = 2 },
                new Band() { BandId = 10, Name = "Empyrean Plague", Genre = "Black Metal", Country = "Canada", LabelRefId = 2 },
                new Band() { BandId = 11, Name = "Finch", Genre = "Post-hardcore", Country = "United States", LabelRefId = 3 },
                new Band() { BandId = 12, Name = "F.A.C.E.", Genre = "Progressive Metal", Country = "Bulgaria", LabelRefId = 3 },
                new Band() { BandId = 13, Name = "Goldfinger", Genre = "Punk Rock", Country = "United States", LabelRefId = 3 },
                new Band() { BandId = 14, Name = "Galen", Genre = "Heavy Metal", Country = "Germany", LabelRefId = 3 },
                new Band() { BandId = 15, Name = "Hammerfall", Genre = "Heavy Metal", Country = "Sweden", LabelRefId = 3 }
            });

            context.Albums.AddOrUpdate(new Album[] {
                new Album() { AlbumId = 1, Name = "City of Evil", ReleaseYear = 2005, BandRefId = 1 },
                new Album() { AlbumId = 2, Name = "All Beyond Perception", ReleaseYear = 2016, BandRefId = 2 },
                new Album() { AlbumId = 3, Name = "Scream Aim Fire", ReleaseYear = 2007, BandRefId = 3 },
                new Album() { AlbumId = 4, Name = "We Are Not Alone", ReleaseYear = 2004, BandRefId = 4 },
                new Album() { AlbumId = 5, Name = "Eaten Back to Life", ReleaseYear = 1990, BandRefId = 5 },
                new Album() { AlbumId = 6, Name = "Hats Off to the Bull", ReleaseYear = 2011, BandRefId = 6 },
                new Album() { AlbumId = 7, Name = "Ten Thousand Fists", ReleaseYear = 2005, BandRefId = 7 },
                new Album() { AlbumId = 8, Name = "Yetzer Ha'ra", ReleaseYear = 2009, BandRefId = 8 },
                new Album() { AlbumId = 9, Name = "Peace, Love, Death Metal", ReleaseYear = 2009, BandRefId = 9 },
                new Album() { AlbumId = 10, Name = "Conquering the Elements", ReleaseYear = 2004, BandRefId = 10 },
                new Album() { AlbumId = 11, Name = "Say Hello to Sunshine", ReleaseYear = 2005, BandRefId = 11 },
                new Album() { AlbumId = 12, Name = "A New Light", ReleaseYear = 2005, BandRefId = 12 },
                new Album() { AlbumId = 13, Name = "Stomping Ground", ReleaseYear = 2000, BandRefId = 13 },
                new Album() { AlbumId = 14, Name = "The Blind lead the Blind", ReleaseYear = 1993, BandRefId = 14 },
                new Album() { AlbumId = 15, Name = "Chapter V: Unbent, Unbowed, Unbroken", ReleaseYear = 2005, BandRefId = 15 },
                new Album() { AlbumId = 16, Name = "Glory to the Brave", ReleaseYear = 1997, BandRefId = 15 }
            });

            context.Tracks.AddOrUpdate(new Track[] {
                // City of Evil
                new Track() { TrackId = 1, Name = "Beast and the Harlot", Length = "5:42", Number = 1, AlbumRefId = 1 },
                new Track() { TrackId = 2, Name = "Burn It Down", Length = "5:00", Number = 2, AlbumRefId = 1 },
                new Track() { TrackId = 3, Name = "Blinded in Chains", Length = "6:34", Number = 3, AlbumRefId = 1 },
                new Track() { TrackId = 4, Name = "Bat Country", Length = "5:13", Number = 4, AlbumRefId = 1 },
                new Track() { TrackId = 5, Name = "Trashed and Scattered", Length = "5:53", Number = 5, AlbumRefId = 1 },
                new Track() { TrackId = 6, Name = "Seize the Day", Length = "5:32", Number = 6, AlbumRefId = 1 },
                new Track() { TrackId = 7, Name = "Sidewinder", Length = "7:01", Number = 7, AlbumRefId = 1 },
                new Track() { TrackId = 8, Name = "The Wicked End", Length = "7:10", Number = 8, AlbumRefId = 1 },
                new Track() { TrackId = 9, Name = "Strength of the World", Length = "9:14", Number = 9, AlbumRefId = 1 },
                new Track() { TrackId = 10, Name = "Betrayed", Length = "6:47", Number = 10, AlbumRefId = 1 },
                new Track() { TrackId = 11, Name = "M.I.A.", Length = "8:48", Number = 11, AlbumRefId = 1 },
                // All Beyond Perception
                new Track() { TrackId = 12, Name = "Protofuture", Length = "5:42", Number = 1, AlbumRefId = 2 },
                new Track() { TrackId = 13, Name = "The Edge", Length = "5:00", Number = 2, AlbumRefId = 2 },
                new Track() { TrackId = 14, Name = "Beyond the Red", Length = "6:34", Number = 3, AlbumRefId = 2 },
                new Track() { TrackId = 15, Name = "Miragem", Length = "5:13", Number = 4, AlbumRefId = 2 },
                new Track() { TrackId = 16, Name = "Onironaut", Length = "5:53", Number = 5, AlbumRefId = 2 },
                new Track() { TrackId = 17, Name = "The Right to be Forgotten", Length = "5:32", Number = 6, AlbumRefId = 2 },
                new Track() { TrackId = 18, Name = "L.u.p.i", Length = "7:01", Number = 7, AlbumRefId = 2 },
                new Track() { TrackId = 19, Name = "Sun", Length = "7:10", Number = 8, AlbumRefId = 2 },
                // Scream Aim Fire
                new Track() { TrackId = 20, Name = "Scream Aim Fire", Length = "5:42", Number = 1, AlbumRefId = 3 },
                new Track() { TrackId = 21, Name = "Eye of the Storm", Length = "5:00", Number = 2, AlbumRefId = 3 },
                new Track() { TrackId = 22, Name = "Hearts Burst into Fire", Length = "6:34", Number = 3, AlbumRefId = 3 },
                new Track() { TrackId = 23, Name = "Waking the Demon", Length = "5:13", Number = 4, AlbumRefId = 3 },
                new Track() { TrackId = 24, Name = "Disappear", Length = "5:53", Number = 5, AlbumRefId = 3 },
                new Track() { TrackId = 25, Name = "Deliver Us from Evil", Length = "5:32", Number = 6, AlbumRefId = 3 },
                new Track() { TrackId = 26, Name = "Take It Out on Me", Length = "7:01", Number = 7, AlbumRefId = 3 },
                new Track() { TrackId = 27, Name = "Say Goodnight", Length = "7:10", Number = 8, AlbumRefId = 3 },
                new Track() { TrackId = 28, Name = "End of Days", Length = "9:14", Number = 9, AlbumRefId = 3 },
                new Track() { TrackId = 29, Name = "Last to Know", Length = "6:47", Number = 10, AlbumRefId = 3 },
                new Track() { TrackId = 30, Name = "Forever and Always", Length = "8:48", Number = 11, AlbumRefId = 3 },
                // We Are Not Alone
                new Track() { TrackId = 31, Name = "So Cold", Length = "5:42", Number = 1, AlbumRefId = 4 },
                new Track() { TrackId = 32, Name = "Simple Design", Length = "5:00", Number = 2, AlbumRefId = 4 },
                new Track() { TrackId = 33, Name = "Follow", Length = "6:34", Number = 3, AlbumRefId = 4 },
                new Track() { TrackId = 34, Name = "Firefly", Length = "5:13", Number = 4, AlbumRefId = 4 },
                new Track() { TrackId = 35, Name = "Break My Fall", Length = "5:53", Number = 5, AlbumRefId = 4 },
                new Track() { TrackId = 36, Name = "Forget It", Length = "5:32", Number = 6, AlbumRefId = 4 },
                new Track() { TrackId = 37, Name = "Sooner or Later", Length = "7:01", Number = 7, AlbumRefId = 4 },
                new Track() { TrackId = 38, Name = "Breakdown", Length = "7:10", Number = 8, AlbumRefId = 4 },
                new Track() { TrackId = 39, Name = "Away", Length = "9:14", Number = 9, AlbumRefId = 4 },
                new Track() { TrackId = 40, Name = "Believe", Length = "6:47", Number = 10, AlbumRefId = 4 },
                new Track() { TrackId = 41, Name = "Rain", Length = "8:48", Number = 11, AlbumRefId = 4 },
                // Eaten Back to Life
                new Track() { TrackId = 42, Name = "Shredded Humans", Length = "5:42", Number = 1, AlbumRefId = 5 },
                new Track() { TrackId = 43, Name = "Edible Autopsy", Length = "5:00", Number = 2, AlbumRefId = 5 },
                new Track() { TrackId = 44, Name = "Put Them to Death", Length = "6:34", Number = 3, AlbumRefId = 5 },
                new Track() { TrackId = 45, Name = "Mangled", Length = "5:13", Number = 4, AlbumRefId = 5 },
                new Track() { TrackId = 46, Name = "Scattered Remains, Splattered Brains", Length = "5:53", Number = 5, AlbumRefId = 5 },
                new Track() { TrackId = 47, Name = "Born in a Casket", Length = "5:32", Number = 6, AlbumRefId = 5 },
                new Track() { TrackId = 48, Name = "Rooting Head", Length = "7:01", Number = 7, AlbumRefId = 5 },
                new Track() { TrackId = 49, Name = "The Undead Will Feast", Length = "7:10", Number = 8, AlbumRefId = 5 },
                new Track() { TrackId = 50, Name = "Bloody Chunks", Length = "9:14", Number = 9, AlbumRefId = 5 },
                new Track() { TrackId = 51, Name = "A Skull Full of Maggots", Length = "6:47", Number = 10, AlbumRefId = 5 },
                new Track() { TrackId = 52, Name = "Buried in the Backyard", Length = "8:48", Number = 11, AlbumRefId = 5 },
                // Hats Off to the Bull
                new Track() { TrackId = 53, Name = "Face to the Floor", Length = "5:42", Number = 1, AlbumRefId = 6 },
                new Track() { TrackId = 54, Name = "Same Old Trip", Length = "5:00", Number = 2, AlbumRefId = 6 },
                new Track() { TrackId = 55, Name = "Ruse", Length = "6:34", Number = 3, AlbumRefId = 6 },
                new Track() { TrackId = 56, Name = "The Meddler", Length = "5:13", Number = 4, AlbumRefId = 6 },
                new Track() { TrackId = 57, Name = "Piñata", Length = "5:53", Number = 5, AlbumRefId = 6 },
                new Track() { TrackId = 57, Name = "Envy", Length = "5:32", Number = 6, AlbumRefId = 6 },
                new Track() { TrackId = 58, Name = "Hats Off to the Bull", Length = "7:01", Number = 7, AlbumRefId = 6 },
                new Track() { TrackId = 59, Name = "Arise", Length = "7:10", Number = 8, AlbumRefId = 6 },
                new Track() { TrackId = 60, Name = "Revenge", Length = "9:14", Number = 9, AlbumRefId = 6 },
                new Track() { TrackId = 61, Name = "Prime Donna", Length = "6:47", Number = 10, AlbumRefId = 6 },
                new Track() { TrackId = 62, Name = "Clones", Length = "8:48", Number = 11, AlbumRefId = 6 },
                // Ten Thousand Fists
                new Track() { TrackId = 63, Name = "Ten Thousand Fists", Length = "5:42", Number = 1, AlbumRefId = 7 },
                new Track() { TrackId = 64, Name = "Just Stop", Length = "5:00", Number = 2, AlbumRefId = 7 },
                new Track() { TrackId = 65, Name = "Guarded", Length = "6:34", Number = 3, AlbumRefId = 7 },
                new Track() { TrackId = 66, Name = "Deify", Length = "5:13", Number = 4, AlbumRefId = 7 },
                new Track() { TrackId = 67, Name = "Stricken", Length = "5:53", Number = 5, AlbumRefId = 7 },
                new Track() { TrackId = 68, Name = "I'm Alive", Length = "5:32", Number = 6, AlbumRefId = 7 },
                new Track() { TrackId = 69, Name = "Sons of Plunder", Length = "7:01", Number = 7, AlbumRefId = 7 },
                new Track() { TrackId = 70, Name = "Overburdened", Length = "7:10", Number = 8, AlbumRefId = 7 },
                new Track() { TrackId = 71, Name = "Decadence", Length = "9:14", Number = 9, AlbumRefId = 7 },
                new Track() { TrackId = 72, Name = "Forgiven", Length = "6:47", Number = 10, AlbumRefId = 7 },
                new Track() { TrackId = 73, Name = "Land of Confusion", Length = "8:48", Number = 11, AlbumRefId = 7 },
                new Track() { TrackId = 74, Name = "Sacred Lie", Length = "8:48", Number = 12, AlbumRefId = 7 },
                new Track() { TrackId = 75, Name = "Pain Redefined", Length = "8:48", Number = 13, AlbumRefId = 7 },
                new Track() { TrackId = 76, Name = "Avarice", Length = "8:48", Number = 14, AlbumRefId = 7 },
                // Yetzer Ha'ra
                new Track() { TrackId = 77, Name = "The Hell in Heaven", Length = "5:42", Number = 1, AlbumRefId = 8 },
                new Track() { TrackId = 78, Name = "The Devil in the Chain", Length = "5:00", Number = 2, AlbumRefId = 8 },
                new Track() { TrackId = 79, Name = "Heaven in Hell", Length = "6:34", Number = 3, AlbumRefId = 8 },
                new Track() { TrackId = 80, Name = "The Maze of Madness", Length = "5:13", Number = 4, AlbumRefId = 8 },
                new Track() { TrackId = 81, Name = "Vicious Circle", Length = "5:53", Number = 5, AlbumRefId = 8 },
                new Track() { TrackId = 82, Name = "The Call", Length = "5:32", Number = 6, AlbumRefId = 8 },
                new Track() { TrackId = 83, Name = "Wind Cry", Length = "7:01", Number = 7, AlbumRefId = 8 },
                // Peace, Love, Death Metal
                new Track() { TrackId = 84, Name = "I Only Want You", Length = "5:42", Number = 1, AlbumRefId = 9 },
                new Track() { TrackId = 85, Name = "Speaking in Tongues", Length = "5:00", Number = 2, AlbumRefId = 9 },
                new Track() { TrackId = 86, Name = "So Easy", Length = "6:34", Number = 3, AlbumRefId = 9 },
                new Track() { TrackId = 87, Name = "Flames Go Higher", Length = "5:13", Number = 4, AlbumRefId = 9 },
                new Track() { TrackId = 88, Name = "Bad Dream Mama", Length = "5:53", Number = 5, AlbumRefId = 9 },
                new Track() { TrackId = 89, Name = "English Girl", Length = "5:32", Number = 6, AlbumRefId = 9 },
                new Track() { TrackId = 90, Name = "Stacks o' Money", Length = "7:01", Number = 7, AlbumRefId = 9 },
                new Track() { TrackId = 91, Name = "Midnight Creeper", Length = "7:10", Number = 8, AlbumRefId = 9 },
                new Track() { TrackId = 92, Name = "Stuck in the Metal", Length = "9:14", Number = 9, AlbumRefId = 9 },
                new Track() { TrackId = 93, Name = "Already Died", Length = "6:47", Number = 10, AlbumRefId = 9 },
                new Track() { TrackId = 94, Name = "Kiss the Devil", Length = "8:48", Number = 11, AlbumRefId = 9 },
                new Track() { TrackId = 95, Name = "Whorehoppin' (Shit, Goddamn)", Length = "8:48", Number = 12, AlbumRefId = 9 },
                new Track() { TrackId = 96, Name = "San Berdoo Sunburn", Length = "8:48", Number = 13, AlbumRefId = 9 },
                new Track() { TrackId = 97, Name = "Wastin' My Time", Length = "8:48", Number = 14, AlbumRefId = 9 },
                new Track() { TrackId = 98, Name = "Miss Alissa", Length = "8:48", Number = 15, AlbumRefId = 9 },
                // Conquering the Elements
                new Track() { TrackId = 99, Name = "Intro", Length = "5:42", Number = 1, AlbumRefId = 10 },
                new Track() { TrackId = 100, Name = "Our Forsaken Homeland", Length = "5:00", Number = 2, AlbumRefId = 10 },
                new Track() { TrackId = 101, Name = "Conquering the Elements", Length = "6:34", Number = 3, AlbumRefId = 10 },
                new Track() { TrackId = 102, Name = "Winds from an Ancient Time", Length = "5:13", Number = 4, AlbumRefId = 10 },
                new Track() { TrackId = 103, Name = "In the Gloom of the Woodland God", Length = "5:53", Number = 5, AlbumRefId = 10 },
                new Track() { TrackId = 104, Name = "The Furthest Shore", Length = "5:32", Number = 6, AlbumRefId = 10 },
                new Track() { TrackId = 105, Name = "The Shroud of Enchantment", Length = "7:01", Number = 7, AlbumRefId = 10 },
                new Track() { TrackId = 106, Name = "Upon Vast Foothills", Length = "7:10", Number = 8, AlbumRefId = 10 },
                new Track() { TrackId = 107, Name = "A Treacherous Road", Length = "9:14", Number = 9, AlbumRefId = 10 },
                new Track() { TrackId = 108, Name = "Outro", Length = "6:47", Number = 10, AlbumRefId = 10 },
                // Say Hello to Sunshine
                new Track() { TrackId = 109, Name = "Insomniatic Meat", Length = "5:42", Number = 1, AlbumRefId = 11 },
                new Track() { TrackId = 110, Name = "Revelation Song", Length = "5:00", Number = 2, AlbumRefId = 11 },
                new Track() { TrackId = 111, Name = "Brother Bleed Brother", Length = "6:34", Number = 3, AlbumRefId = 11 },
                new Track() { TrackId = 112, Name = "A Piece of Mind", Length = "5:13", Number = 4, AlbumRefId = 11 },
                new Track() { TrackId = 113, Name = "Ink", Length = "5:53", Number = 5, AlbumRefId = 11 },
                new Track() { TrackId = 114, Name = "Fireflies", Length = "5:32", Number = 6, AlbumRefId = 11 },
                new Track() { TrackId = 115, Name = "Hopeless Host", Length = "7:01", Number = 7, AlbumRefId = 11 },
                new Track() { TrackId = 116, Name = "Reduced to Teeth", Length = "7:10", Number = 8, AlbumRefId = 11 },
                new Track() { TrackId = 117, Name = "A Man Alone", Length = "9:14", Number = 9, AlbumRefId = 11 },
                new Track() { TrackId = 118, Name = "Miro", Length = "6:47", Number = 10, AlbumRefId = 11 },
                new Track() { TrackId = 119, Name = "Ravenous", Length = "8:48", Number = 11, AlbumRefId = 11 },
                new Track() { TrackId = 120, Name = "Bitemarks and Bloodstains", Length = "8:48", Number = 12, AlbumRefId = 11 },
                new Track() { TrackId = 121, Name = "The Casket of Roderick Usher", Length = "8:48", Number = 13, AlbumRefId = 11 },
                new Track() { TrackId = 122, Name = "Dreams of Psilocybin", Length = "8:48", Number = 14, AlbumRefId = 11 },
                // A New Light
                new Track() { TrackId = 123, Name = "Fly", Length = "5:42", Number = 1, AlbumRefId = 12 },
                new Track() { TrackId = 124, Name = "Do Not Care", Length = "5:00", Number = 2, AlbumRefId = 12 },
                new Track() { TrackId = 125, Name = "The Top", Length = "6:34", Number = 3, AlbumRefId = 12 },
                new Track() { TrackId = 126, Name = "Nightmare", Length = "5:13", Number = 4, AlbumRefId = 12 },
                new Track() { TrackId = 127, Name = "Sober Mind", Length = "5:53", Number = 5, AlbumRefId = 12 },
                new Track() { TrackId = 128, Name = "Hate and Passion", Length = "5:32", Number = 6, AlbumRefId = 12 },
                new Track() { TrackId = 129, Name = "Insane", Length = "7:01", Number = 7, AlbumRefId = 12 },
                new Track() { TrackId = 130, Name = "Little Black Devil", Length = "7:10", Number = 8, AlbumRefId = 12 },
                new Track() { TrackId = 131, Name = "A New Light", Length = "9:14", Number = 9, AlbumRefId = 12 },
                // Stomping Ground
                new Track() { TrackId = 132, Name = "I'm Down", Length = "5:42", Number = 1, AlbumRefId = 13 },
                new Track() { TrackId = 133, Name = "Pick a Fight", Length = "5:00", Number = 2, AlbumRefId = 13 },
                new Track() { TrackId = 134, Name = "Carry On", Length = "6:34", Number = 3, AlbumRefId = 13 },
                new Track() { TrackId = 135, Name = "The End of the Day", Length = "5:13", Number = 4, AlbumRefId = 13 },
                new Track() { TrackId = 136, Name = "Don't Say Goodbye", Length = "5:53", Number = 5, AlbumRefId = 13 },
                new Track() { TrackId = 137, Name = "Counting the Days", Length = "5:32", Number = 6, AlbumRefId = 13 },
                new Track() { TrackId = 138, Name = "Bro", Length = "7:01", Number = 7, AlbumRefId = 13 },
                new Track() { TrackId = 139, Name = "San Simeon", Length = "7:10", Number = 8, AlbumRefId = 13 },
                new Track() { TrackId = 140, Name = "You Think It's a Joke", Length = "9:14", Number = 9, AlbumRefId = 13 },
                new Track() { TrackId = 141, Name = "Forgiveness", Length = "6:47", Number = 10, AlbumRefId = 13 },
                new Track() { TrackId = 142, Name = "Margaret Ann", Length = "8:48", Number = 11, AlbumRefId = 13 },
                new Track() { TrackId = 143, Name = "Get Away", Length = "8:48", Number = 12, AlbumRefId = 13 },
                new Track() { TrackId = 144, Name = "99 Red Ballons", Length = "8:48", Number = 13, AlbumRefId = 13 },
                new Track() { TrackId = 145, Name = "Donut Dan", Length = "8:48", Number = 14, AlbumRefId = 13 },
                // The Blind lead the Blind
                new Track() { TrackId = 146, Name = "Eye to Eye", Length = "5:42", Number = 1, AlbumRefId = 14 },
                new Track() { TrackId = 147, Name = "Stainless Steel", Length = "5:00", Number = 2, AlbumRefId = 14 },
                new Track() { TrackId = 148, Name = "Digger", Length = "6:34", Number = 3, AlbumRefId = 14 },
                new Track() { TrackId = 149, Name = "Alone", Length = "5:13", Number = 4, AlbumRefId = 14 },
                new Track() { TrackId = 150, Name = "End of Evolution", Length = "5:53", Number = 5, AlbumRefId = 14 },
                // Chapter V: Unbent, Unbowed, Unbroken
                new Track() { TrackId = 151, Name = "Secrets", Length = "5:42", Number = 1, AlbumRefId = 15 },
                new Track() { TrackId = 152, Name = "Blood Bound", Length = "5:00", Number = 2, AlbumRefId = 15 },
                new Track() { TrackId = 153, Name = "Fury of the Wild", Length = "6:34", Number = 3, AlbumRefId = 15 },
                new Track() { TrackId = 154, Name = "Hammer of Justice", Length = "5:13", Number = 4, AlbumRefId = 15 },
                new Track() { TrackId = 155, Name = "Never, Ever", Length = "5:53", Number = 5, AlbumRefId = 15 },
                new Track() { TrackId = 156, Name = "Born to Rule", Length = "5:32", Number = 6, AlbumRefId = 15 },
                new Track() { TrackId = 157, Name = "The Templar Flame", Length = "7:01", Number = 7, AlbumRefId = 15 },
                new Track() { TrackId = 158, Name = "Imperial", Length = "7:10", Number = 8, AlbumRefId = 15 },
                new Track() { TrackId = 159, Name = "Take the Black", Length = "9:14", Number = 9, AlbumRefId = 15 },
                new Track() { TrackId = 161, Name = "Knights of the 21st Century", Length = "6:47", Number = 10, AlbumRefId = 15 },
                // Glory to the Brave
                new Track() { TrackId = 162, Name = "The Dragon Lies Bleeding", Length = "5:42", Number = 1, AlbumRefId = 16 },
                new Track() { TrackId = 163, Name = "The Metal Age", Length = "5:00", Number = 2, AlbumRefId = 16 },
                new Track() { TrackId = 164, Name = "I Believe", Length = "6:34", Number = 3, AlbumRefId = 16 },
                new Track() { TrackId = 165, Name = "Child of the Damned", Length = "5:13", Number = 4, AlbumRefId = 16 },
                new Track() { TrackId = 166, Name = "Steel Meets Steel", Length = "5:53", Number = 5, AlbumRefId = 16 },
                new Track() { TrackId = 167, Name = "Stone Cold", Length = "5:32", Number = 6, AlbumRefId = 16 },
                new Track() { TrackId = 168, Name = "Unchained", Length = "7:01", Number = 7, AlbumRefId = 16 },
                new Track() { TrackId = 169, Name = "Glory to the Brave", Length = "7:10", Number = 8, AlbumRefId = 16 },
                new Track() { TrackId = 170, Name = "Ravenlord", Length = "9:14", Number = 9, AlbumRefId = 16 },
                new Track() { TrackId = 171, Name = "Hammerfall", Length = "6:47", Number = 10, AlbumRefId = 16 },
                new Track() { TrackId = 172, Name = "Glory to the Brave", Length = "8:48", Number = 11, AlbumRefId = 16 }
            });
        }
    }
}
